### PR TITLE
saving fix

### PR DESCRIPTION
**Pull request by fps01**
Hello!
I found a small bug in `updateInternal()` method. It losed some fields because `getDirtyAttributes()` returns only updated values.

**Case:**
I have a model `User` with fields id, name, password.

``` php
$user = new User;
$user->id = 5;
$user->name = 'test';
$user->password = 'test_password';
$user->save();

$user = User::findOne(5);
$user->password = 'new password';
$user->save();
```

Here I have only id and password in db file.

### CODE REVIEW

**Comment by klimov-paul** [comment]
Can you add a unit test for your issue?

**Comment by fps01** [comment]
Of course.

**Comment by klimov-paul** [comment]
OK, I am waiting.

**Comment by fps01** [comment]
@klimov-paul Done!

**Comment by klimov-paul** [comment]
Merged, thank you.

**Pull request merged**
